IF
  HotKey(S)
  CombatCounter(0)
  OR(2)
    !Class(Myself,Monk)
    Global("ikmorph_monk_allowed","GLOBAL",1)
THEN
  RESPONSE #100
    ReallyForceSpellRES("IKMorph",Myself)
END

IF
  HotKey(S)
  !CombatCounter(0)
THEN
  RESPONSE #100
    DisplayString(Myself,@0)
END

IF
  HotKey(S)
  CombatCounter(0)
  Class(Myself,Monk)
  !Global("ikmorph_monk_allowed","GLOBAL",1)
THEN
  RESPONSE #100
    DisplayString(Myself,@1)
END
