IF
	Global("cdt_spawn_eldoth","MYAREA",0)
	LevelLT(Player1,5)
THEN
	RESPONSE #100
		SetGlobal("cdt_spawn_eldoth","MYAREA",1)
		CreateCreature("ELDOTH",[%x_coord%.%y_coord%],%orient%)  // Eldoth
END

IF
	Global("cdt_spawn_eldoth","MYAREA",0)
	LevelGT(Player1,4)
THEN
	RESPONSE #100
		SetGlobal("cdt_spawn_eldoth","MYAREA",1)
		CreateCreature("ELDOTH5",[%x_coord%.%y_coord%],%orient%)  // Eldoth
END