/////                                                            \\\\\
///// all                                                        \\\\\
/////                                                            \\\\\

EXTEND_BOTTOM ~AR0602.BCS~ ~%MOD_FOLDER%/baf/start_500k.baf~
EXTEND_BOTTOM ~AR0602.BCS~ ~%MOD_FOLDER%/baf/start_tomes.baf~
EXTEND_BOTTOM ~AR0602.BCS~ ~%MOD_FOLDER%/baf/start_pantaloons.baf~
EXTEND_BOTTOM ~AR0602.BCS~ ~%MOD_FOLDER%/baf/start_drizzt.baf~
EXTEND_BOTTOM ~AR0602.BCS~ ~%MOD_FOLDER%/baf/start_balduran.baf~
