DEFINE_ACTION_FUNCTION "DIVINE_GRACE_DARK_BLESSING"
BEGIN
	LAF "GT_ADD_SPELL"
	INT_VAR
		"level" = 1
		"type" = 4
	STR_VAR
		"idsName" = "PALADIN_DIVINE_GRACE"
	RET
		"PALADIN_DIVINE_GRACE" = "resName"
	END
	//
	LAF "GT_ADD_SPELL"
	INT_VAR
		"level" = 1
		"type" = 4
	STR_VAR
		"idsName" = "BLACKGUARD_DARK_BLESSING"
	RET
		"BLACKGUARD_DARK_BLESSING" = "resName"
	END
	//
	WITH_SCOPE BEGIN
		ACTION_TO_LOWER "BLACKGUARD_DARK_BLESSING"
		ACTION_TO_LOWER "PALADIN_DIVINE_GRACE"
		COPY "cdtweaks\luke\bam\kit\dark_blessing.bam" "override\%BLACKGUARD_DARK_BLESSING%d.bam"
		COPY "cdtweaks\luke\bam\class\divine_grace.bam" "override\%PALADIN_DIVINE_GRACE%d.bam"
	END
	//
	WITH_SCOPE BEGIN
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@0) STR_VAR "bam_file" = "%PALADIN_DIVINE_GRACE%D" RET "feedback_icon_paladin" = "index" END
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@1) STR_VAR "bam_file" = "%BLACKGUARD_DARK_BLESSING%D" RET "feedback_icon_blackguard" = "index" END
		// Listener: run 'func' each time a sprite has finished evaluating its effects
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Misc Tweaks (Class / Kit)" "sourceFileSpec" = "cdtweaks\luke\lua\class\divine_grace.lua" "destRes" = "m_gtspcl" END
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Misc Tweaks (Class / Kit)" "sourceFileSpec" = "cdtweaks\luke\lua\kit\dark_blessing.lua" "destRes" = "m_gtspcl" END
		//
		ACTION_IF !(FILE_EXISTS_IN_GAME "m_gttbls.lua") BEGIN
			COPY "cdtweaks\luke\lua\m_gttbls.lua" "override"
		END
	END
END