DEFINE_ACTION_FUNCTION "OIWD-STYLE_STR_BONUSES"
BEGIN
	COPY_EXISTING "x-iwdstr.2da" "override"
		COUNT_2DA_COLS "cols"
		READ_2DA_ENTRIES_NOW ~entries~ "%cols%"
		//
		FOR ("i" = 0 ; "%i%" < "%entries%" ; "i" += 1) BEGIN
			READ_2DA_ENTRY_FORMER "entries" "%i%" 0 "label"
			PATCH_IF ("%label%" STR_EQ "CHECK_MODE") BEGIN
				SET_2DA_ENTRY "%i%" 1 "%cols%" 1 // enable
				SET "i" = "%entries%" // kill FOR-loop
			END
		END
	BUT_ONLY_IF_IT_CHANGES
END

