DEFINE_ACTION_FUNCTION "REVISED_INNS"
BEGIN
	WITH_SCOPE BEGIN
		COPY "cdtweaks\luke\bam\rule_changes\well_rested.bam" "override\gtrule04.bam"
		//
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@0) STR_VAR "bam_file" = "GTRULE04" RET "feedback_icon" = "index" END
		//
		LAF "APPEND_LUA_CHUNK" STR_VAR "description" = "Rule Changes" "sourceFileSpec" = "cdtweaks\luke\lua\rule_changes\revised_inns.lua" "destRes" = "m_gtrule" END
	END
	//
	<<<<<<<< .../cdtweaks-inlined/revised_inns.baf
	IF
		GlobalGT("gtTweaksRevisedInnsRoomType","GLOBAL",0)
		PartyRested()
	THEN
		RESPONSE #100
			EEex_LuaAction("GT_TweaksAnthology_RevisedInns()")
			SetGlobal("gtTweaksRevisedInnsRoomType","GLOBAL",0)
			Continue()
	END
	>>>>>>>>
	// getting and patching list of world scripts
	LAF "GET_WORLD_SCRIPTS" RET_ARRAY "world_scripts" = "toReturn" END
	ACTION_PHP_EACH "world_scripts" AS "resref" => "" BEGIN
		EXTEND_TOP "%resref%.bcs" ".../cdtweaks-inlined/revised_inns.baf" BUT_ONLY IF_EXISTS
	END
END

