DEFINE_ACTION_FUNCTION "WOODLAND_STRIDE"
BEGIN
	LAF "GT_ADD_SPELL"
	INT_VAR
		"level" = 6
		"type" = 4
		"preferredSlot" = 43
	STR_VAR
		"idsName" = "DRUID_WOODLAND_STRIDE"
	RET
		"DRUID_WOODLAND_STRIDE" = "resName"
	END
	//
	WITH_SCOPE BEGIN
		ACTION_TO_LOWER "DRUID_WOODLAND_STRIDE"
		COPY "cdtweaks\luke\bam\class\woodland_stride.bam" "override\%DRUID_WOODLAND_STRIDE%d.bam" // courtesy of zenblack
	END
	//
	WITH_SCOPE BEGIN
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@0) STR_VAR "bam_file" = "%DRUID_WOODLAND_STRIDE%D" RET "feedback_icon" = "index" END
		// Listener(s)
		LAF "APPEND_LUA_CHUNK" STR_VAR "description" = "Class/Kit Abilities" "sourceFileSpec" = "cdtweaks\luke\lua\class\woodland_stride.lua" "destRes" = "m_gtspcl" END
		LAF "APPEND_LUA_CHUNK" STR_VAR "description" = "Sprites" "sourceFileSpec" = "cdtweaks\luke\lib\sprite\check_ids.lua" "destRes" = "m_gtsprt" END
		// immunities via 403
		LAF "IMMUNITY_REMOVAL" STR_VAR "path" = "cdtweaks\luke\lib" END
		//
		ACTION_IF !(FILE_EXISTS_IN_GAME "m_gttbls.lua") BEGIN
			COPY "cdtweaks\luke\lib\resource\tables.lua" "override\m_gttbls.lua"
		END
	END
END

