DEFINE_ACTION_FUNCTION "MAKE_GREASE_IGNITABLE"
BEGIN
	ACTION_IF !(FILE_EXISTS_IN_GAME "SOFLAMC.BAM") BEGIN
		COPY "cdtweaks\luke\bam\soflamc.bam" "override"
	END
	ACTION_IF !(FILE_EXISTS_IN_GAME "#SHROUD.VVC") BEGIN
		COPY "cdtweaks\luke\vvc\#shroud.vvc" "override"
	END
	ACTION_IF !(FILE_EXISTS_IN_GAME "MISC_01C.WAV") BEGIN
		COPY "cdtweaks\luke\wav\misc_01c.wav" "override"
	END
	//
	LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Misc Tweaks" "sourceFileSpec" = "cdtweaks\luke\lua\tweaks\make_grease_ignitable.lua" "destRes" = "m_gttwks" END
END