DEFINE_ACTION_FUNCTION "POISON_SAVE"
BEGIN
	LAF "GT_ADD_SPELL"
	INT_VAR
		"type" = 4
		"level" = 4
	STR_VAR
		"idsName" = "ASSASSIN_POISON_SAVE"
	RET
		"ASSASSIN_POISON_SAVE" = "resName"
	END
	//
	WITH_SCOPE BEGIN
		ACTION_TO_LOWER "ASSASSIN_POISON_SAVE"
		COPY "cdtweaks\luke\bam\kit\poison_save.bam" "override\%ASSASSIN_POISON_SAVE%d.bam"
	END
	//
	LAF "ADD_EXTENDED_STAT" STR_VAR "identifier" = "GT_IMMUNITIES_VIA_403" END
	// immunities via 403
	LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Lua Tools" "sourceFileSpec" = "cdtweaks\luke\lua\tool\array_contains.lua" "destRes" = "m_gttool" END
	LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Immunities via 403" "sourceFileSpec" = "cdtweaks\luke\lua\immunity.lua" "destRes" = "m_gt#imm" END
	LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "AI-related stuff" "sourceFileSpec" = "cdtweaks\luke\lua\ai\object_type.lua" "destRes" = "m_gt#ai" END
	//
	WITH_SCOPE BEGIN
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@0) STR_VAR "bam_file" = "%ASSASSIN_POISON_SAVE%D" RET "feedback_icon" = "index" END
		// Listener: run 'func' each time a sprite has finished evaluating its effects
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Class/Kit Abilities" "sourceFileSpec" = "cdtweaks\luke\lua\kit\poison_save.lua" "destRes" = "m_gtspcl" END
	END
	//
	ACTION_IF !(FILE_EXISTS_IN_GAME "m_gttbls.lua") BEGIN
		COPY "cdtweaks\luke\lua\m_gttbls.lua" "override"
	END
END