DEFINE_ACTION_FUNCTION "WEAPON_FINESSE"
BEGIN
	WITH_SCOPE BEGIN
		COPY "cdtweaks\bam\gtwpnfin.bam" "override"
	END
	//
	WITH_SCOPE BEGIN
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@0) STR_VAR "bam_file" = "gtwpnfin" RET "feedback_icon" = "index" END
		// Listener: run 'func' each time a sprite has finished evaluating its effects
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Misc Tweaks (Class)" "sourceFileSpec" = "cdtweaks\luke\lua\class\weapon_finesse.lua" "destRes" = "m_gtclss" END
		//
		ACTION_IF !(FILE_EXISTS_IN_GAME "m_gttbls.lua") BEGIN
			COPY "cdtweaks\luke\lua\m_gttbls.lua" "override"
		END
	END
END