DEFINE_ACTION_FUNCTION "WEAPON_FINESSE"
BEGIN
	LAF "GT_ADD_SPELL"
	INT_VAR
		"type" = 4
		"level" = 4
	STR_VAR
		"idsName" = "ROGUE_WEAPON_FINESSE"
	RET
		"ROGUE_WEAPON_FINESSE" = "resName"
	END
	//
	WITH_SCOPE BEGIN
		ACTION_TO_LOWER "ROGUE_WEAPON_FINESSE"
		COPY "cdtweaks\luke\bam\class\weapon_finesse.bam" "override\%ROGUE_WEAPON_FINESSE%d.bam"
	END
	//
	WITH_SCOPE BEGIN
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@0) STR_VAR "bam_file" = "%ROGUE_WEAPON_FINESSE%D" RET "feedback_icon" = "index" END
		// Listener: run 'func' each time a sprite has finished evaluating its effects
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Misc Tweaks (Class / Kit)" "sourceFileSpec" = "cdtweaks\luke\lua\class\weapon_finesse.lua" "destRes" = "m_gtspcl" END
		//
		ACTION_IF !(FILE_EXISTS_IN_GAME "m_gttbls.lua") BEGIN
			COPY "cdtweaks\luke\lua\m_gttbls.lua" "override"
		END
	END
END